included:
  - packages
  - apps

excluded:
  - .build
  - Derived
  - build
  - vendor
  - "**/*.generated.swift"

disabled_rules:
  - todo
  - trailing_comma

line_length:
  warning: 140
  error: 200

identifier_name:
  min_length: 1
  excluded:
    - id
    - x
    - y
    - r
    - g
    - b
    - lo
    - hi

type_name:
  min_length: 2

function_body_length:
  warning: 80
  error: 150
