/** Screenshots are generated by `mise run screenshots` and synced from docs/images. */

export type Shot = { src: string; alt: string; caption: string; width: number; height: number };

const app = (file: string, alt: string, caption: string): Shot => ({
  src: `/synced/images/${file}`,
  alt,
  caption,
  width: 1800,
  height: 991,
});

const harness = (file: string, alt: string, caption: string): Shot => ({
  src: `/synced/images/${file}`,
  alt,
  caption,
  width: 1800,
  height: 850,
});

/** Captured by hand, so `mise run screenshots` leaves it alone. */
export const heroShot = app(
  "hero.png",
  "Redlamp editing a Sony α7R V raw file of a dancer at a street parade, with the Develop panels on the right",
  "Editing a Sony α7R V raw file.",
);

export type Feature = {
  id: string;
  eyebrow: string;
  title: string;
  body: string[];
  points: string[];
  shot?: Shot;
};

export const features: Feature[] = [
  {
    id: "develop",
    eyebrow: "Develop",
    title: "Lightroom's workflow, at home on the Mac.",
    body: [
      "The Develop module's layout, panel order, slider names, ranges and defaults, and single-key shortcuts all carry over, so there's nothing to relearn. Everything underneath is rebuilt as a native, GPU-first app.",
    ],
    points: [
      "Basic, Tone Curve, Color Mixer, Color Grading, Detail and Effects",
      "Lightroom Classic's shortcuts: 80 actions on 84 key bindings",
      "Find an adjustment (⌘F) by name, or by the words people use",
      "Before and after in three layouts, cached so edits never re-render it",
    ],
    shot: app(
      "before-after.png",
      "Before and after, side by side, on a Nikon Z 6 raw file",
      "Before and after on a Nikon Z 6 NEF: Exposure, Highlights, Shadows, Dehaze, Clarity and Vibrance.",
    ),
  },
  {
    id: "speed",
    eyebrow: "Responsiveness",
    title: "Every slider lands within a frame.",
    body: [
      "One fused Metal kernel applies every adjustment, frames arrive as IOSurfaces without a copy, and rendering never waits on the main thread. Drag a slider and the photo keeps up.",
    ],
    points: [
      "Interactive renders at Fit in 0.6 to 3 ms on Apple Silicon",
      "A full 26 MP frame at 1:1 in about 13 ms",
      "Latest-wins scheduling: a burst of slider events collapses to the newest",
      "A full mip pyramid, so every zoom level samples the right resolution",
    ],
    shot: app(
      "zoom-xtrans.png",
      "A Fujifilm X-T3 X-Trans raw file at 100%, with the Color Mixer in HSL mode",
      "A Fujifilm X-T3 X-Trans RAF at 1:1, rendered in about 13 ms.",
    ),
  },
  {
    id: "masking",
    eyebrow: "Masking",
    title: "Masks are part of the architecture, not an afterthought.",
    body: [
      "Every edit is a layer: its own adjustments plus a mask built from components that add, subtract and intersect, exactly as in Lightroom. Masks are evaluated per pixel inside the same GPU kernel, so 16 of them cost well under a millisecond.",
    ],
    points: [
      "Linear and radial gradients, drawn and adjusted on the photo",
      "15 local adjustments, including Texture, Clarity and Dehaze",
      "A red mask overlay, and a full mask list",
      "Brush, colour range and on-device AI masks are next",
    ],
    shot: app(
      "masking.png",
      "Masking on a Sony A7 III raw file, with the red mask overlay over the sky",
      "A linear gradient darkens and cools the sky; a feathered radial gradient warms the trees.",
    ),
  },
  {
    id: "color",
    eyebrow: "Colour",
    title: "Serious colour science, scene-referred from the start.",
    body: [
      "The pipeline is linear and scene-referred, with a proper camera white-balance model. The Color Mixer works in OKLCh, so hues move the way your eye expects, and some looks are measured against cameras' own renderings.",
    ],
    points: [
      "Temperature and Tint with Robertson's method and the camera's matrix",
      "3-way and individual colour-grading wheels, with Blending and Balance",
      "Parametric and point tone curves",
      "Measured looks: Standard v3 sits within ΔE 3.26 of the camera's Provia",
    ],
    shot: app(
      "color-grading.png",
      "Colour grading a Canon EOS R6 raw file with the 3-way wheels",
      "Split-toned shadows and highlights on a Canon EOS R6 CR3.",
    ),
  },
  {
    id: "detail",
    eyebrow: "Detail",
    title: "Noise reduction that knows your camera's noise.",
    body: [
      "Noise reduction scales to each photo's own noise, read from the DNG or measured from the raw data when it opens. Sharpening measures detail on a denoised copy, so grain passes through untouched instead of being sharpened.",
    ],
    points: [
      "Luminance and Color noise reduction with Lightroom's controls",
      "Noise-aware sharpening, from unsharp mask towards deconvolution",
      "Texture, Clarity and Dehaze, globally and inside masks",
      "Highlight reconstruction rebuilds clipped photosites",
    ],
    shot: app(
      "detail.png",
      "A Canon EOS R6 raw file at 100% with the Detail panel open",
      "Detail at 1:1 on a Canon EOS R6 CR3.",
    ),
  },
  {
    id: "recipes",
    eyebrow: "Recipes",
    title: "Presets, profiles and LUTs, finally in one place.",
    body: [
      "A Recipe is anything that gives a photo a look. One open format holds presets, profiles (a recipe's Base Look) and LUTs, and you can type in a Fujifilm-style camera recipe card exactly as it's written.",
    ],
    points: [
      "39 bundled recipes in eight groups, with hover to preview",
      "Import and export .redrecipe, .cube and HaldCLUT",
      "Camera controls: Dynamic Range, Color Chrome and white-balance shift",
      "The Recipe Lab checks every look across a 40-image set",
    ],
    shot: app(
      "recipes.png",
      "A camera recipe applied to a Fujifilm X-T3 raw file",
      "Chrome Street, built from a Fujifilm-style recipe card, on the measured Chrome Base Look.",
    ),
  },
  {
    id: "raw",
    eyebrow: "Our own RAW pipeline",
    title: "Your originals are never touched.",
    body: [
      "LibRaw only unpacks the file. Black levels, white balance, demosaicing and colour all happen in Redlamp, on the GPU. Edits are saved to a small sidecar next to each photo, and the original stays exactly as you shot it.",
    ],
    points: [
      "Menon demosaic for Bayer sensors, and X-Trans support",
      "Hot-pixel repair, banding correction and DNG gain maps",
      "Sony ARW, Canon CR3, Nikon NEF, Fujifilm RAF, Apple ProRAW and Pixel DNG",
      "Plus JPEG, HEIC, TIFF and PNG",
    ],
    shot: app(
      "proraw.png",
      "An iPhone 12 Pro ProRAW file in portrait orientation",
      "iPhone 12 Pro ProRAW, with highlight recovery and blues tuned in the Color Mixer.",
    ),
  },
];

export const focusStacking = {
  eyebrow: "Focus stacking",
  title: "Focus stacking in one click, and it still develops like a raw.",
  body: "Redlamp spots a focus bracket in your folder and offers to merge it. Frames are stacked as demosaiced camera RGB before any edit, so every Develop slider still works on the result, and you can retouch from any frame.",
  points: [
    "Stacks are detected for you, with a Merge banner",
    "Auto, Smooth and Detail strategies, and a depth map",
    "25 Canon CR3 frames merge in about 8 seconds",
  ],
};

export const commandPalette = {
  eyebrow: "Command palette",
  title: "Find anything, then adjust it without leaving the keyboard.",
  body: "⌘K opens one search for every action, every Develop slider and every picker. Choosing a slider or a picker doesn't close the palette: it turns into that control, over the photo.",
  footer: "A hint bar always shows the keys that work right now, and each opening shows a tip.",
};

/** Close-ups of the palette in the harness's Live scene, cropped by `mise run screenshots`. */
const closeUp = (file: string, alt: string) => ({ src: `/synced/images/${file}`, alt, width: 1600, height: 1000 });

export type PaletteStep = { keys: string[]; title: string; body: string; image: ReturnType<typeof closeUp> };

export const paletteSteps: PaletteStep[] = [
  {
    keys: ["⌘K"],
    title: "Search everything",
    body: "Every action with its shortcut beside it, every slider, and pickers for white balance, treatment, Base Looks, recipes, Before / After, snapshots and history. ⌘F searches the sliders alone.",
    image: closeUp(
      "palette-search.png",
      "The command palette searching for “white”: the White Balance and Treatment pickers, the Temp, Tint, Whites and Saturation sliders with their values, and actions with their shortcuts",
    ),
  },
  {
    keys: ["↵", "← →", "↑ ↓"],
    title: "Adjust from the keyboard",
    body: "↵ on a slider shrinks the palette to a slider bar over the photo. ← → step it, ⇧ ten times as far and ⌥ finer, ↑ ↓ move to the next slider, and a run of presses is one history step.",
    image: closeUp(
      "palette-slider.png",
      "The palette shrunk to a slider bar for Exposure at +0.50 over the photo, with its keys beside the track and in a hint bar",
    ),
  },
  {
    keys: ["↑ ↓", "↵", "Esc"],
    title: "Preview before you apply",
    body: "Moving through a picker previews each choice on the photo. ↵ applies the choice, and Esc goes back one level.",
    image: closeUp(
      "palette-picker.png",
      "The Base Look picker with Redlamp Monochrome highlighted and previewing on the photo, which shows in black and white",
    ),
  },
  {
    keys: ["↵"],
    title: "Type the value",
    body: "A name and a value, such as `exposure 0.7` or `temp 5600k`, sets the slider straight from the search. In the slider bar, type a value or `x+0.3`.",
    image: closeUp("palette-value.png", "The palette with “temp 5600k” typed, offering to set Temp from 5000 to 5600"),
  },
];

export const performance = [
  { value: "70–250 ms", label: "to open a 24–26 MP raw file" },
  { value: "0.6–3 ms", label: "per interactive render at Fit" },
  { value: "~13 ms", label: "for a full 26 MP frame at 1:1" },
  { value: "~45 ms", label: "for a full-resolution export render" },
];

export const principles = [
  {
    title: "Instantly familiar",
    body: "Lightroom's panels, slider names, ranges and shortcuts. Conventions copied, never Adobe's assets.",
  },
  {
    title: "Masks from day one",
    body: "Every edit is a layer with a mask, combined by add, subtract and intersect, with on-device AI masks to come.",
  },
  {
    title: "Native, neutral UI",
    body: "macOS 26 design, Liquid Glass only on floating chrome, and neutral grey wherever you judge colour.",
  },
  {
    title: "Under 16 ms",
    body: "Rendering and UI are strictly separated. The UI never waits on the engine, the disk or the GPU.",
  },
  {
    title: "Serious colour",
    body: "Scene-referred and linear, with camera profiles, LUTs and looks fitted by measurement.",
  },
  {
    title: "Computational photography",
    body: "Best-in-class denoise, one-click focus stacking, and AI only where it clearly wins, on the device.",
  },
  {
    title: "Mac first",
    body: "One platform-neutral engine. The Mac editor comes first; iPad and iPhone follow from the same engine.",
  },
  {
    title: "Open source",
    body: "MPL-2.0, compatible with the App Store, with algorithms implemented clean-room from papers.",
  },
];

export const gallery: Shot[] = [
  app(
    "black-and-white.png",
    "Black and white on a Sony A7 III raw file",
    "The Selenium recipe plus vignette and grain, with every step in History.",
  ),
  app("film-editor.png", "CineStill 800T applied in the editor", "CineStill 800T, with its grain, halation and bloom."),
  harness(
    "lab-gallery.png",
    "The Recipe Lab gallery and split compare",
    "The Recipe Lab: every look on a 40-image set, with a split compare.",
  ),
  harness(
    "lab-across-set.png",
    "One recipe across the look-development set",
    "One recipe across landscapes, animals, night streets and interiors.",
  ),
  harness("lab-side-by-side.png", "Two recipes side by side", "Chrome Street against Bright Slide."),
  harness("lab-inspect.png", "Inspecting a recipe in the Recipe Lab", "Every setting, the camera card and the table's lint."),
  harness(
    "harness-parity.png",
    "The component harness comparing SwiftUI and AppKit panels",
    "The component harness checks every AppKit panel against its SwiftUI original, pixel for pixel.",
  ),
  harness("harness-tokens.png", "Design tokens in the harness", "The palette, type ramp and metrics."),
];
