/**
 * The 11 film simulations, from the README's catalogue and
 * packages/RedlampRecipes/Sources/Film/FilmLookCatalog.swift. Icons and sample sheets are
 * regenerated by `redlamp recipe film --all --install --readme` and synced from docs/.
 */

export type FilmFamily = "negative" | "cinema" | "slide" | "bw";

export type Film = {
  id: string;
  name: string;
  maker: string;
  stock: string;
  family: FilmFamily;
  kind: string;
  iso: number | null;
  rendered: string;
  grain: number;
  halation: number;
  bloom?: number;
  description: string;
};

export const families: { id: FilmFamily | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "negative", label: "Colour negative" },
  { id: "cinema", label: "Cinema" },
  { id: "slide", label: "Slide" },
  { id: "bw", label: "Black and white" },
];

export const films: Film[] = [
  {
    id: "portra-400",
    name: "Portra 400",
    maker: "Kodak",
    stock: "Kodak Portra 400",
    family: "negative",
    kind: "Colour negative",
    iso: 400,
    rendered: "Scanned, Frontier-like",
    grain: 20,
    halation: 8,
    description:
      "Warm and gentle. Kind to skin, with soft greens and a little extra warmth in the highlights, as a Frontier lab scan renders it.",
  },
  {
    id: "ektar-100",
    name: "Ektar 100",
    maker: "Kodak",
    stock: "Kodak Ektar 100",
    family: "negative",
    kind: "Colour negative",
    iso: 100,
    rendered: "Scanned, Frontier-like",
    grain: 8,
    halation: 6,
    description: "Kodak's finest-grained colour negative: richer reds and deeper colour than Portra.",
  },
  {
    id: "gold-200",
    name: "Gold 200",
    maker: "Kodak",
    stock: "Kodak Gold 200",
    family: "negative",
    kind: "Colour negative",
    iso: 200,
    rendered: "Scanned, Frontier-like",
    grain: 23,
    halation: 9,
    description: "Warm consumer film. Golden yellows, slightly greener foliage and more grain.",
  },
  {
    id: "superia-400",
    name: "Superia 400",
    maker: "Fujifilm",
    stock: "Fujifilm Superia X-Tra 400",
    family: "negative",
    kind: "Colour negative",
    iso: 400,
    rendered: "Scanned, Frontier-like",
    grain: 24,
    halation: 8,
    description: "Cooler than the Kodak stocks, with Fujifilm's greens.",
  },
  {
    id: "cinestill-800t",
    name: "CineStill 800T",
    maker: "CineStill",
    stock: "CineStill 800T",
    family: "negative",
    kind: "Tungsten colour negative",
    iso: 800,
    rendered: "Scanned, Noritsu-like",
    grain: 26,
    halation: 70,
    bloom: 8,
    description:
      "Vision3 500T without its anti-halation backing. Bright lights glow red-orange, the look of night streets and neon.",
  },
  {
    id: "vision3-500t-2383",
    name: "Vision3 500T · 2383",
    maker: "Kodak",
    stock: "Kodak Vision3 500T on 2383 print film",
    family: "cinema",
    kind: "Cinema negative on print film",
    iso: 500,
    rendered: "Printed on 2383 and projected",
    grain: 24,
    halation: 14,
    bloom: 6,
    description:
      "The motion-picture look: a cinema negative printed on release print film. Softer and denser, with cool shadows and warm highlights.",
  },
  {
    id: "provia-100f",
    name: "Provia 100F",
    maker: "Fujifilm",
    stock: "Fujifilm Provia 100F",
    family: "slide",
    kind: "Slide film",
    iso: 100,
    rendered: "Slide, viewed on a light box",
    grain: 8,
    halation: 4,
    description: "Clean, natural slide film. Contrasty, with deep skies and dense shadows, exposed for the highlights.",
  },
  {
    id: "velvia-50",
    name: "Velvia 50",
    maker: "Fujifilm",
    stock: "Fujifilm Velvia 50",
    family: "slide",
    kind: "Slide film",
    iso: 50,
    rendered: "Slide, viewed on a light box",
    grain: 9,
    halation: 4,
    description: "The landscape slide: saturated greens, yellows and blues, and more contrast still.",
  },
  {
    id: "tri-x-400",
    name: "Tri-X 400",
    maker: "Kodak",
    stock: "Kodak Tri-X 400",
    family: "bw",
    kind: "Black and white negative",
    iso: 400,
    rendered: "Scanned",
    grain: 37,
    halation: 5,
    description: "Classic black and white. Bright and crisp, with pronounced, sharp grain.",
  },
  {
    id: "hp5-plus",
    name: "HP5 Plus",
    maker: "Ilford",
    stock: "Ilford HP5 Plus",
    family: "bw",
    kind: "Black and white negative",
    iso: 400,
    rendered: "Scanned",
    grain: 40,
    halation: 5,
    description: "Softer and grainier than Tri-X, with a gentler shoulder.",
  },
  {
    id: "tri-x-multigrade",
    name: "Tri-X · Darkroom Print",
    maker: "Kodak / Ilford",
    stock: "Kodak Tri-X printed on Ilford Multigrade paper, grade 2",
    family: "bw",
    kind: "Black and white print",
    iso: null,
    rendered: "Printed on paper",
    grain: 34,
    halation: 5,
    description: "A darkroom print: deeper blacks and the paper's own contrast.",
  },
];

export const filmIcon = (id: string) => `/synced/film/icon-${id}.png`;
export const filmSample = (id: string) => `/synced/film/look-${id}.jpg`;

export const filmTrademarks =
  "Kodak, Portra, Ektar, Gold, Vision3, Tri-X, Fujifilm, Superia, Provia, Velvia, Ilford, HP5, Multigrade and CineStill are trademarks of their owners. Redlamp isn't affiliated with them: its looks are built from the published technical data.";

export const filmFaithfulness = [
  "The colour comes from the datasheets: each stock's own curves, sensitivities and dyes, keeping their published order of contrast and grain.",
  "A lab's scan or print timing shapes the rest. The Frontier-like and Noritsu-like scanner profiles are characterised from how labs describe them, not measured.",
  "Some data is borrowed or uncertain: Portra, Ektar, Gold and Superia borrow Vision3's dye curves, and the 2383 sensitivity curve is the least certain trace.",
  "Grain doesn't yet vary with density, and is sized in pixels rather than relative to the frame.",
];
